name: Build Docker image and publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.repository_owner == 'lens0021' && github.ref == 'refs/heads/main' }}
          tags: ghcr.io/lens0021/nowiki:latest
