name: Build Docker image and publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        if: github.repository_owner == 'lens0021' && github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.repository_owner == 'lens0021' && github.ref == 'refs/heads/main' }}
          tags: ghcr.io/lens0021/this-is-not-a-wiki:latest
